{% set version = "1.25.2" %}

package:
  name: urllib3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/urllib3/urllib3-{{ version }}.tar.gz
  sha256: a53063d8b9210a7bdec15e7b272776b9d42b2fd6816401a0d43006ad2f9902db

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    # secure
    - pyopenssl >=0.14
    - cryptography >=1.3.4
    - idna >=2.0.0
    - certifi
    - ipaddress  # [py<=33]
    - pysocks >=1.5.6,<2.0,!=1.5.7

test:
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.packages
    - urllib3.packages.backports
    - urllib3.packages.ssl_match_hostname
    - urllib3.util

about:
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'HTTP library with thread-safe connection pooling, file post, and more.'
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/shazow/urllib3

extra:
  recipe-maintainers:
    - pmlandwehr
    - sigmavirus24
    - ocefpaf
