{% set version = "1.26.5" %}

package:
  name: urllib3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/urllib3/urllib3-{{ version }}.tar.gz
  sha256: a7acd0977125325f516bda9735fa7142b909a8d01e8b2e4c8108d0984e6e0098

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python <4.0
    - pip
  run:
    - python <4.0
    # optional deps [secure]
    - pyopenssl >=0.14
    - cryptography >=1.3.4
    - idna >=2.0.0
    - certifi
    # optional deps [socks]
    - pysocks >=1.5.6,<2.0,!=1.5.7
    # optional deps [brotli]
    - brotlipy >=0.6.0


test:
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.packages
    - urllib3.packages.backports
    - urllib3.packages.ssl_match_hostname
    - urllib3.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/shazow/urllib3

extra:
  recipe-maintainers:
    - pmlandwehr
    - sigmavirus24
    - ocefpaf
    - sethmlarson
