{% set name = "urllib3" %}
{% set version = "1.26.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urllib3-{{ version }}.tar.gz
  sha256: 8a388717b9476f934a21484e8c8e61875ab60644d29b9b39e11e4b9dc1c6b305

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python <4.0
  run:
    - python <4.0
    # optional deps [secure]
    - pyopenssl >=0.14
    - cryptography >=1.3.4
    - idna >=2.0.0
    - certifi
    # optional deps [socks]
    - pysocks >=1.5.6,<2.0,!=1.5.7
    # optional deps [brotli]
    - brotlipy >=0.6.0


test:
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.packages
    - urllib3.packages.backports
    - urllib3.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/shazow/urllib3

extra:
  recipe-maintainers:
    - shazow
    - sethmlarson
