{% set name = "urllib3" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urllib3-{{ version }}.tar.gz
  sha256: da21131828d290d6331d0d93a18f062ead1ec4fe0cfebbcefc95ee5368f7188a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - hatchling >=1.6.0,<2
    - pip
  run:
    - python >=3.7
    # optional deps [socks]
    - pysocks >=1.5.6,<2.0,!=1.5.7
    # optional deps [brotli]
    - brotli >=1.0.9


test:
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/shazow/urllib3

extra:
  recipe-maintainers:
    - shazow
    - sethmlarson
    - ocefpaf
