{% set name = "urllib3" %}
{% set version = "1.21" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "d0f08f1472754890c8b228106eb831a7a68c93565bd0818936c30bb839913647" %}
{% set build_num %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyopenssl >=0.14
    - cryptography >=1.3.4
    - idna >=2.0.0
    - certifi
    - ipaddress
    - pysocks >=1.5.6,<2.0,!=1.5.7

test:
  imports:
    - urllib3
    - urllib3.packages
    - urllib3.packages.ssl_match_hostname
    - urllib3.packages.backports
    - urllib3.contrib
    - urllib3.contrib._securetransport
    - urllib3.util

about:
  home: https://urllib3.readthedocs.io/
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: 'HTTP library with thread-safe connection pooling, file post, and more.'
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/shazow/urllib3

extra:
  recipe-maintainers:
    - pmlandwehr
    - sigmavirus24
    - ocefpaf
