{% set name = "urllib3" %}
{% set version = "2.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urllib3-{{ version }}.tar.gz
  sha256: e7d814a81dad81e6caf2ec9fdedb284ecc9c73076b62654547cc64ccdcae26e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling >=1.6.0,<2
    - hatch-vcs ==0.4.0
    - pip
  run:
    - python >=3.8
    # optional deps [socks]
    - pysocks >=1.5.6,<2.0,!=1.5.7
    # optional deps [brotli]
    - brotli-python >=1.0.9
    # optional deps [zstandard]
    - zstandard >=0.18.0
    # optional deps [h2]
    - h2 >=4,<5


test:
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/shazow/urllib3

extra:
  recipe-maintainers:
    - shazow
    - sethmlarson
    - ocefpaf
    - pquentin
    - illia-v
