schema_version: 1

context:
  name: urllib3
  version: "2.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/urllib3-${{ version }}.tar.gz
  sha256: 3fc47733c7e419d4bc3f6b3dc2b4f890bb743906a30d56ba4a5bfa4bbff92760

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.6.0,<2
    - hatch-vcs ==0.4.0
    - pip
  run:
    - python >=${{ python_min }}
    # optional deps [socks]
    - pysocks >=1.5.6,<2.0,!=1.5.7
    # optional deps [brotli]
    - brotli-python >=1.0.9
    # optional deps [zstandard]
    - zstandard >=0.18.0
    # optional deps [h2]
    - h2 >=4,<5

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - urllib3
        - urllib3.contrib
        - urllib3.util
      pip_check: true

about:
  homepage: https://urllib3.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  documentation: https://urllib3.readthedocs.io/
  repository: https://github.com/shazow/urllib3

extra:
  recipe-maintainers:
    - shazow
    - sethmlarson
    - ocefpaf
    - pquentin
    - illia-v
